### ISSUE TITLE
Cogs Inside the Building Spawn Without Nametags

### ISSUE THREAD

**Issue by ooowoothevirtualhowler** [robertfwallis/toontownsfunnyfarm-issue-tracker#14]
Title and image say all. It's strange because they did in the previous version.

![funnyfarm-screenshot-Sun-Jan-19-17-02-10-2020-881131](https://user-images.githubusercontent.com/46305034/72689282-df7e4800-3add-11ea-83ec-8c4a3970335f.jpg)

**Comment by NathanX-S** [comment]
Fixed for v1.4.3! Thanks for the report. 🎉

**Comment by ToonInvasion** [comment]
I just wanted to comment that this is still appearing like this for me, I just did this task today.

**Comment by robertfwallis** [comment]
> I just wanted to comment that this is still appearing like this for me, I just did this task today.

This has been fixed on the development version of the game, but has yet to be released into any form of public update due to goings-ons within the team.
